---
apiVersion: v1
kind: Pod
metadata:
  name: go-app-pod
  labels:
    app: go-app
spec:
  imagePullSecrets:
    - name: ghcr-secret
  containers:
    - name: go-app
      image: ghcr.io/k4l1br1/containers-lab-1-bts-16/app:latest
      ports:
        - containerPort: 8080
      env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "secret"
        - name: DB_NAME
          value: "myapp"
